# Generated by Django 3.1.8 on 2021-04-25 13:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_scheduled_tasks', models.IntegerField(default=1, help_text='Maximum number of allowed scheduled tasks', validators=[django.core.validators.MinValueValidator(1, message='Rating is to small'), django.core.validators.MaxValueValidator(5, message='Rating to too large')], verbose_name='Max Scheduled Tasks')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Household ID')),
                ('name', models.CharField(help_text='Household name', max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(help_text='Household member list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
