# Generated by Django 3.1.8 on 2021-04-25 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Task ID')),
                ('name', models.CharField(help_text='Task name', max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('interval', models.IntegerField(help_text='Interval in seconds', verbose_name='Interval')),
                ('time_to_complete', models.IntegerField(help_text='How much time on average does it take to complete the task in seconds', verbose_name='Takes Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_completed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('handlers', models.ManyToManyField(help_text='Task handlers', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.household')),
            ],
        ),
    ]
